version: '3.5'
services:
  flyway:
    image: flyway/flyway
    command: -url='jdbc:mysql://mysql:3306/interview?allowPublicKeyRetrieval=true&permitMysqlScheme=true' -schemas=interview -user=admin -password=admin -baselineOnMigrate=true -connectRetries=60 migrate
    volumes:
      - ./src/migrations:/flyway/sql
    depends_on:
      mysql:
        condition: service_healthy
    # networks:
    #   - interview-network

  mysql:
    image: mysql:8.0.36
    container_name: mysql_interview
    environment:
      - MYSQL_DATABASE=interview
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    command: --sql_generate_invisible_primary_key=ON
    volumes:
      - interview-volume:/var/lib/mysql
    ports:
      - 3308:3306
    # networks:
    #   - interview-network
    restart: unless-stopped
    healthcheck:
      test: "mysql -h mysql -uadmin -padmin interview -e 'SELECT 1;'"
      interval: 10s
      retries: 10

# networks:
#    interview-network:
#     driver: bridge

volumes:
  interview-volume: